#Find the Difference

Description:
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.


One Method: 

Convert the two string into array then sort them
loop through the array until a character doesn't match
with each other and break out of loop
return the character that didn't match


class Solution {

    /**
     * @param String $s
     * @param String $t
     * @return String
     */
    function findTheDifference($s, $t) {

        $s = str_split($s);
        $t = str_split($t);
        
        sort($s);
        sort($t);
        
        $str_char = '';
        while (!empty($t)){
            $str_char = array_shift($t);
            if ($str_char != array_shift($s)){
                break;
            }
        }

        return $str_char;
    }
}